default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= Rails.application.credentials.db_dev %>

test:
  <<: *default
  url: <%= Rails.application.credentials.db_test %>

production:
  <<: *default
  url: <%= Rails.application.credentials.db %>
