service: work_design
image: work-design/work_design
deploy_timeout: 100
servers:
  web:
    hosts:
      - shu.ren
  job:
    hosts:
      - shu.ren
    cmd: bin/jobs

registry:
  server: ccr.ccs.tencentyun.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - ~/app/acme:/rails/acme
  - ~/app/tmp/storage:/rails/tmp/storage

env:
  clear:
    RAILS_ENV: production
    RAILS_MAX_THREADS: 6
    HOST: shu.ren
  secret:
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY

builder:
  dockerfile: deploy/Dockerfile
  arch: x86_64
  remote: ssh://ubuntu@49.235.150.128

accessories:
  postgres:
    image: ccr.ccs.tencentyun.com/kamal/postgres:x86_64
    host: shu.ren
    port: 5432
    env:
      clear:
        POSTGRES_INITDB_ARGS: -c include_if_exists=/var/lib/postgresql/custom.conf
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
      - ~/app/db_dump:/root/pg_dump
    files:
      - deploy/postgresql.conf:/var/lib/postgresql/custom.conf

proxy:
  hosts:
    - shu.ren
  ssl: true
  app_port: 3000
  response_timeout: 100
  forward_headers: true
  healthcheck:
    interval: 5
    timeout: 150
