service: work
image: work-design/work
deploy_timeout: 100
servers:
  web:
    hosts:
      - <%= ENV['HOST'] %>

registry:
  server: ccr.ccs.tencentyun.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - ~/app/acme:/rails/acme
  - ~/app/tmp/storage:/rails/tmp/storage
  - ~/app/storage:/rails/storage

env:
  clear:
    RAILS_ENV: production
    RAILS_MAX_THREADS: 20
    HOST: <%= ENV['HOST'] %>

ssh:
  key_data:
    - <%= ENV['PRIVATE_KEY'] %>
  keys_only: true

builder:
  dockerfile: deploy/Dockerfile
  arch: x86_64
  remote: ssh://ubuntu@49.235.150.128

proxy:
  host: <%= ENV['HOST'] %>
  ssl: true
  app_port: 3000
  response_timeout: 100
  forward_headers: true
  healthcheck:
    interval: 30
    timeout: 60
