development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: '*'
      threads: 3
      polling_interval: 2
test:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: '*'
      threads: 3
      polling_interval: 2
production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: '*'
      threads: 3
      polling_interval: 2
