local:
  service: Disk
  root: <%= Rails.root.join('storage_local') %>

acme:
  service: Disc
  root: <%= Rails.root.join('acme') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
