class RailsComRenameModule < ActiveRecord::Migration[6.1]

  def change
    rename_table :accounts, :auth_accounts
    rename_table :verify_tokens, :auth_verify_tokens
    rename_table :users, :auth_users
    rename_table :oauth_users, :auth_oauth_users
    rename_table :user_tags, :auth_user_tags
    rename_table :user_taggeds, :auth_user_taggeds
    rename_table :authorized_tokens, :auth_authorized_tokens
    rename_table :profiles, :profiled_profiles
    rename_table :areas, :profiled_areas
    rename_table :address_users, :profiled_address_users
    rename_table :addresses, :profiled_addresses
    rename_table :area_hierarchies, :profiled_area_hierarchies
    rename_table :trade_items, :trade_trade_items
    rename_table :promote_goods, :trade_promote_goods
    rename_table :orders, :trade_orders
    rename_table :payments, :trade_payments
    rename_table :refunds, :trade_refunds
    rename_table :promote_carts, :trade_promote_carts
    rename_table :card_advances, :trade_card_advances
    rename_table :payment_references, :trade_payment_references
    rename_table :cards, :trade_cards
    rename_table :advances, :trade_advances
    rename_table :cash_givens, :trade_cash_givens
    rename_table :card_logs, :trade_card_logs
    rename_table :cash_logs, :trade_cash_logs
    rename_table :promote_charges, :trade_promote_charges
    rename_table :payouts, :trade_payouts
    rename_table :payment_strategies, :trade_payment_strategies
    rename_table :promote_extras, :trade_promote_extras
    rename_table :payment_methods, :trade_payment_methods
    rename_table :card_templates, :trade_card_templates
    rename_table :card_promotes, :trade_card_promotes
    rename_table :cashes, :trade_cashes
    rename_table :trade_promotes, :trade_trade_promotes
    rename_table :carts, :trade_carts
    rename_table :payment_orders, :trade_payment_orders
    rename_table :organs, :org_organs
    rename_table :members, :org_members
    rename_table :departments, :org_departments
    rename_table :resign_references, :org_resign_references
    rename_table :job_descriptions, :org_job_descriptions
    rename_table :member_departments, :org_member_departments
    rename_table :organ_domains, :org_organ_domains
    rename_table :job_titles, :org_job_titles
    rename_table :supports, :org_supports
    rename_table :resign_reasons, :org_resign_reasons
    rename_table :super_job_titles, :org_super_job_titles
    rename_table :job_transfers, :org_job_transfers
    rename_table :resigns, :org_resigns
    rename_table :tutorials, :org_tutorials
    rename_table :department_grants, :org_department_grants
    rename_table :organ_handles, :org_organ_handles
    rename_table :organ_hierarchies, :org_organ_hierarchies
    rename_table :department_hierarchies, :org_department_hierarchies
    rename_table :notifications, :notice_notifications
    rename_table :notification_sendings, :notice_notification_sendings
    rename_table :annunciations, :notice_annunciations
    rename_table :user_annunciates, :notice_user_annunciates
    rename_table :member_annunciates, :notice_member_annunciates
    rename_table :attitudes, :interact_attitudes
    rename_table :stars, :interact_stars
    rename_table :comments, :interact_comments
    rename_table :abuses, :interact_abuses
    rename_table :financial_taxons, :finance_financial_taxons
    rename_table :fund_incomes, :finance_fund_incomes
    rename_table :expense_items, :finance_expense_items
    rename_table :stocks, :finance_stocks
    rename_table :budgets, :finance_budgets
    rename_table :expense_members, :finance_expense_members
    rename_table :assessments, :finance_assessments
    rename_table :funds, :finance_funds
    rename_table :expenses, :finance_expenses
    rename_table :financial_taxon_hierarchies, :finance_financial_taxon_hierarchies
    rename_table :productions, :factory_productions
    rename_table :production_parts, :factory_production_parts
    rename_table :part_items, :factory_part_items
    rename_table :parts, :factory_parts
    rename_table :production_items, :factory_production_items
    rename_table :product_produces, :factory_product_produces
    rename_table :product_plans, :factory_product_plans
    rename_table :products, :factory_products
    rename_table :part_taxons, :factory_part_taxons
    rename_table :product_taxons, :factory_product_taxons
    rename_table :factory_taxons, :factory_factory_taxons
    rename_table :produce_plans, :factory_produce_plans
    rename_table :product_parts, :factory_product_parts
    rename_table :factory_providers, :factory_factory_providers
    rename_table :product_part_taxons, :factory_product_part_taxons
    rename_table :production_carts, :factory_production_carts
    rename_table :part_providers, :factory_part_providers
    rename_table :produces, :factory_produces
    rename_table :part_plans, :factory_part_plans
    rename_table :part_taxon_hierarchies, :factory_part_taxon_hierarchies
    rename_table :product_taxon_hierarchies, :factory_product_taxon_hierarchies
    rename_table :taxon_items, :detail_taxon_items
    rename_table :knowledges, :detail_knowledges
    rename_table :items, :detail_items
    rename_table :post_syncs, :detail_post_syncs
    rename_table :knowings, :detail_knowings
    rename_table :contents, :detail_contents
    rename_table :lists, :detail_lists
    rename_table :posts, :detail_posts
    rename_table :entity_items, :detail_entity_items
    rename_table :knowledge_hierarchies, :detail_knowledge_hierarchies
    rename_table :absences, :attend_absences
    rename_table :attendance_logs, :attend_attendance_logs
    rename_table :attendance_settings, :attend_attendance_settings
    rename_table :absence_stats, :attend_absence_stats
    rename_table :attendances, :attend_attendances
    rename_table :financial_months, :attend_financial_months
    rename_table :extra_days, :attend_extra_days
    rename_table :attendance_stats, :attend_attendance_stats
    rename_table :overtimes, :attend_overtimes
    rename_table :agencies, :agential_agencies
    rename_table :verifiers, :auditor_verifiers
    rename_table :approvals, :auditor_approvals
    rename_table :audits, :auditor_audits
    rename_table :verifications, :auditor_verifications
    rename_table :who_roles, :roled_who_roles
    rename_table :rule_operations, :roled_rule_operations
    rename_table :busynesses, :roled_busynesses
    rename_table :role_rules, :roled_role_rules
    rename_table :rules, :roled_rules
    rename_table :roles, :roled_roles
    rename_table :name_spaces, :roled_name_spaces
    rename_table :governs, :roled_governs
    rename_table :role_types, :roled_role_types
    rename_table :table_items, :datum_table_items
    rename_table :table_lists, :datum_table_lists
    rename_table :record_lists, :datum_record_lists
    rename_table :data_lists, :datum_data_lists
  end

end
