class RailsComRemoveTable < ActiveRecord::Migration[6.1]

  def change
    drop_table :accessories
    drop_table :active_storage_blob_defaults
    #drop_table :spatial_ref_sys
    drop_table :annunciates
    drop_table :card_expenses
    drop_table :card_returns
    drop_table :cart_promotes
    drop_table :charges
    drop_table :check_settings
    drop_table :checks
    drop_table :custom_carts
    drop_table :custom_parts
    drop_table :customs
    drop_table :details
    drop_table :govern_taxon_hierarchies
    drop_table :good_partners
    drop_table :good_produces
    drop_table :good_providers
    drop_table :govern_taxons
    drop_table :links
    drop_table :logs
    drop_table :maintain_sources
    drop_table :maintain_logs
    drop_table :maintain_source_templates
    drop_table :maintain_tag_templates
    drop_table :maintain_tags
    drop_table :maintains
    drop_table :money_givens
    drop_table :notification_settings
    drop_table :notify_settings
    drop_table :organ_tokens
    drop_table :payment_types
    drop_table :pictures
    drop_table :product_items
    drop_table :project_funds
    drop_table :project_members
    drop_table :project_preferences
    drop_table :providers
    drop_table :quip_threads
    drop_table :rally_users
    drop_table :rallies
    drop_table :record_items
    drop_table :requirement_volunteers
    drop_table :serve_goods
    drop_table :taggeds
    drop_table :tags
    drop_table :taxon_hierarchies
    drop_table :taxons
    drop_table :team_members
    drop_table :teams
    drop_table :user_providers
    drop_table :volunteers
    drop_table :wait_lists
    drop_table :wait_items
    drop_table :wait_taxons
    drop_table :wechat_request_replies
    drop_table :wechat_tag_defaults
    drop_table :whos
  end

end
